/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: a.aazhgirevich (https://sketchfab.com/a.aazhgirevich)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/wrist-watch-88a72f698eda415d8217de52c86a650a
Title: Wrist watch
*/

import React, { useEffect, useRef } from 'react'
import { MeshTransmissionMaterial, useGLTF, useTexture } from '@react-three/drei'
import * as THREE from 'three'
import gsap from 'gsap';

export function Watch({click,...props}) {
  const { nodes, materials } = useGLTF('/wrist_watch.glb')
  const leather = useTexture('/leather.jpg');
  leather.wrapS = leather.wrapT = THREE.RepeatWrapping;
  leather.repeat.set(6, 6); // Adjust the repeat values as needed
  const glass = useRef();
  const hr = useRef();
  const min = useRef();
  const sec = useRef();
  const hours = useRef();
  const minutes = useRef();
  const nums = useRef();
  useEffect(()=>{
    gsap.to(glass.current.position,{
      y: click ? 1.5 : -0.632,
      duration: 1,
    })
    gsap.to(hr.current.position,{
      y: click ? 1 : 0,
      duration: 1,
    })
    gsap.to(min.current.position,{
      y: click ? 1 : 0,
      duration: 1,
    })
    gsap.to(sec.current.position,{
      y: click ? 1 : 0,
      duration: 1,
    })
    gsap.to(hours.current.position,{
      y: click ? 1 : 0,
      duration: 1,
    })
    gsap.to(hours.current.rotation,{
      y: click ? 3.14 : 0,
      duration: 1.5,
    })
    gsap.to(minutes.current.position,{
      y: click ? 1 : .5,
      duration: 1,
    })
    gsap.to(minutes.current.rotation,{
      y: click ? 3.14 : 0.5,
      duration: 1.5,
    })
    gsap.to(nums.current.position,{
      y: click ? 1 : 0.5,
      duration: 1,
    })
    
  },[click])
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials.Shiny_Metal}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_5.geometry}
        material={materials.material_0}
      >
        <meshPhysicalMaterial color={"white"} roughness={1} metalness={0} side={THREE.DoubleSide} />
      </mesh>
      <group position={[-0.007, -0.632, 0.19]} scale={1.005}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_11.geometry}
          material={materials.Shiny_Metal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_12.geometry}
          material={materials.Shiny_Metal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_13.geometry}
          material={materials.Shiny_Metal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_14.geometry}
          material={materials.Shiny_Metal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_15.geometry}
          material={materials.Shiny_Metal}
        />
      </group>
      <group position={[-0.417, -1.302, 0.015]} rotation={[-3.139, 0.026, -2.057]} scale={1.005}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_19.geometry}
          material={materials.Rough_leather}
        >
            <meshPhysicalMaterial  color={"gray"} roughness={1} metalness={0}  />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_20.geometry}
          material={materials.Shiny_Metal}
        />
      </group>
      <group position={[-0.007, -0.632, 0.19]} scale={1.005}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_22.geometry}
          material={materials.Shiny_Metal}
          ref={hours}
        />
        <group position={[-0.237, 0.448, -0.737]} scale={[0.24, 0.24, 0.161]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_30.geometry}
            material={materials.Brushed__Dark_Metal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_32.geometry}
            material={materials.Brushed__Dark_Metal}
            position={[0.448, 0.011, 0.597]}
            scale={[0.476, 0.476, 0.713]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_34.geometry}
            material={materials.Brushed__Dark_Metal}
            position={[-0.208, -0.01, 8.613]}
            scale={[1.345, 1.345, 2.013]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_36.geometry}
            material={materials.Brushed__Dark_Metal}
            position={[-0.821, 0.012, 13.578]}
            rotation={[0, -0.112, 0]}
            scale={[0.493, 0.543, 0.81]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_38.geometry}
            material={materials.Brushed__Dark_Metal}
            position={[1.368, -0.003, 13.744]}
            rotation={[0, 0.071, 0]}
            scale={[0.489, 0.488, 0.729]}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_24.geometry}
          material={materials.Shiny_Metal}
          position={[-0.029, 0.456, -1.604]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.018, 0.003, 0.129]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_26.geometry}
          material={materials.Shiny_Metal}
          position={[0.056, 0.456, -1.604]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.018, 0.003, 0.129]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_28.geometry}
          material={materials.Brushed__Dark_Metal}
          position={[0.673, 0.447, 1.124]}
          rotation={[0, 0.542, 0]}
          scale={0.125}
          ref={nums}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_40.geometry}
          material={materials.Shiny_Metal}
          position={[0.031, 0.454, -0.914]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.085, 0.016, 0.042]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_42.geometry}
          material={materials.Brushed__Dark_Metal}
          position={[-0.12, 0.43, -0.186]}
          rotation={[-Math.PI, 0, 0]}
          scale={[-0.016, 0.016, 0.052]}
          ref={minutes}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_7.geometry}
        material={materials.Shiny_Metal}
        position={[-0.007, -0.176, 0.002]}
        rotation={[-Math.PI, 0, 0]}
        scale={[-0.036, 0.081, 0.036]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_9.geometry}
        material={materials.Shiny_Metal}
        position={[-0.007, -0.168, 0.002]}
        rotation={[-Math.PI, 0, 0]}
        scale={[-0.088, 0.01, 0.088]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_17.geometry}
        material={materials.Shiny_Metal}
        position={[-0.007, -0.632, 0.19]}
        scale={1.005}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_44.geometry}
        material={materials.Clean_Beckmann_Glass}
        position={[-0.007, -0.632, 0.19]}
        scale={1.005}
        ref={glass}
      >
        <MeshTransmissionMaterial thickness={.2} color={"#FAF9F6"} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_46.geometry}
        material={materials.Shiny_Metal}
        position={[-0.007, -0.146, 0.002]}
        rotation={[-Math.PI, 0.507, 0]}
        scale={[-0.088, 0.008, 0.088]}
        ref={hr}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_48.geometry}
        material={materials.Shiny_Metal}
        position={[-0.007, -0.131, 0.002]}
        rotation={[0, -0.003, -Math.PI]}
        scale={[-0.088, 0.008, 0.088]}
        ref={min}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_50.geometry}
        material={materials.Shiny_Metal}
        position={[-0.007, -0.114, 0.002]}
        rotation={[0, 0.832, -Math.PI]}
        scale={[-0.093, 0.007, 0.093]}
        ref={sec}
      />
    </group>
  )
}

useGLTF.preload('/wrist_watch.glb')
